package com.bytemyth.gms_installer.catalog

enum class ComponentGroup {
    Core,
    Apps,
}

data class GmsComponent(
    val id: String,
    val packageName: String,
    val title: String,
    val summary: String,
    val group: ComponentGroup,
    val order: Int,
    val required: Boolean,
)

object GmsCatalog {
    val all: List<GmsComponent> = listOf(
        GmsComponent(
            id = "gsf",
            packageName = "com.google.android.gsf",
            title = "服务框架",
            summary = "Google Services Framework，账号和推送的底座，必须最先安装。",
            group = ComponentGroup.Core,
            order = 10,
            required = true,
        ),
        GmsComponent(
            id = "account",
            packageName = "com.google.android.gsf.login",
            title = "账号管理",
            summary = "Google 账号登录组件。新版系统有时已并入服务框架。",
            group = ComponentGroup.Core,
            order = 20,
            required = false,
        ),
        GmsComponent(
            id = "play_services",
            packageName = "com.google.android.gms",
            title = "Play 服务",
            summary = "Google Play 服务，地图、登录、推送都依赖它。",
            group = ComponentGroup.Core,
            order = 30,
            required = true,
        ),
        GmsComponent(
            id = "play_store",
            packageName = "com.android.vending",
            title = "Play 商店",
            summary = "用来下载和更新其余 Google 应用。",
            group = ComponentGroup.Core,
            order = 40,
            required = true,
        ),
        GmsComponent(
            id = "partner",
            packageName = "com.google.android.partnersetup",
            title = "合作伙伴设置",
            summary = "部分机型补齐商店配置时会用到。",
            group = ComponentGroup.Core,
            order = 50,
            required = false,
        ),
        GmsComponent(
            id = "contacts_sync",
            packageName = "com.google.android.syncadapters.contacts",
            title = "联系人同步",
            summary = "把 Google 联系人同步到本机。",
            group = ComponentGroup.Core,
            order = 60,
            required = false,
        ),
        GmsComponent(
            id = "calendar_sync",
            packageName = "com.google.android.syncadapters.calendar",
            title = "日历同步",
            summary = "把 Google 日历同步到本机。",
            group = ComponentGroup.Core,
            order = 70,
            required = false,
        ),
        GmsComponent(
            id = "chrome",
            packageName = "com.android.chrome",
            title = "Chrome",
            summary = "浏览器。",
            group = ComponentGroup.Apps,
            order = 110,
            required = false,
        ),
        GmsComponent(
            id = "gmail",
            packageName = "com.google.android.gm",
            title = "Gmail",
            summary = "邮件。",
            group = ComponentGroup.Apps,
            order = 120,
            required = false,
        ),
        GmsComponent(
            id = "search",
            packageName = "com.google.android.googlequicksearchbox",
            title = "Google",
            summary = "搜索与助理。",
            group = ComponentGroup.Apps,
            order = 130,
            required = false,
        ),
        GmsComponent(
            id = "maps",
            packageName = "com.google.android.apps.maps",
            title = "地图",
            summary = "Google 地图。",
            group = ComponentGroup.Apps,
            order = 140,
            required = false,
        ),
        GmsComponent(
            id = "youtube",
            packageName = "com.google.android.youtube",
            title = "YouTube",
            summary = "视频。",
            group = ComponentGroup.Apps,
            order = 150,
            required = false,
        ),
        GmsComponent(
            id = "photos",
            packageName = "com.google.android.apps.photos",
            title = "相册",
            summary = "Google 相册。",
            group = ComponentGroup.Apps,
            order = 160,
            required = false,
        ),
        GmsComponent(
            id = "gboard",
            packageName = "com.google.android.inputmethod.latin",
            title = "Gboard",
            summary = "输入法。",
            group = ComponentGroup.Apps,
            order = 170,
            required = false,
        ),
        GmsComponent(
            id = "messages",
            packageName = "com.google.android.apps.messaging",
            title = "信息",
            summary = "Google 信息。",
            group = ComponentGroup.Apps,
            order = 180,
            required = false,
        ),
        GmsComponent(
            id = "calendar",
            packageName = "com.google.android.calendar",
            title = "日历",
            summary = "Google 日历应用。",
            group = ComponentGroup.Apps,
            order = 190,
            required = false,
        ),
        GmsComponent(
            id = "contacts",
            packageName = "com.google.android.contacts",
            title = "通讯录",
            summary = "Google 通讯录。",
            group = ComponentGroup.Apps,
            order = 200,
            required = false,
        ),
        GmsComponent(
            id = "drive",
            packageName = "com.google.android.apps.docs",
            title = "云端硬盘",
            summary = "Drive。",
            group = ComponentGroup.Apps,
            order = 210,
            required = false,
        ),
        GmsComponent(
            id = "keep",
            packageName = "com.google.android.keep",
            title = "Keep",
            summary = "笔记。",
            group = ComponentGroup.Apps,
            order = 220,
            required = false,
        ),
        GmsComponent(
            id = "translate",
            packageName = "com.google.android.apps.translate",
            title = "翻译",
            summary = "Google 翻译。",
            group = ComponentGroup.Apps,
            order = 230,
            required = false,
        ),
        GmsComponent(
            id = "yt_music",
            packageName = "com.google.android.apps.youtube.music",
            title = "YouTube Music",
            summary = "音乐。",
            group = ComponentGroup.Apps,
            order = 240,
            required = false,
        ),
        GmsComponent(
            id = "meet",
            packageName = "com.google.android.apps.tachyon",
            title = "Meet",
            summary = "视频通话。",
            group = ComponentGroup.Apps,
            order = 250,
            required = false,
        ),
        GmsComponent(
            id = "play_games",
            packageName = "com.google.android.play.games",
            title = "Play 游戏",
            summary = "游戏登录与成就。",
            group = ComponentGroup.Apps,
            order = 260,
            required = false,
        ),
    )

    private val byPackage = all.associateBy { it.packageName }

    fun find(packageName: String): GmsComponent? = byPackage[packageName]
}
